builders:
  api_builder:
    import: 'package:service_package/api/api_builder.dart'
    builder_factories: ['apiBuilder']
    build_extensions: {'.dart': ['.response.dart']}
    auto_apply: root_package
    build_to: source